domain:
  default:
    executable:
      restart: true
    server:
      instances: 2
      restart: true
  executables: []
  name: ${POD_NAME}
  global:
    service:
      execution:
        timeout:
          duration: 90s
  groups:
    - dependencies:
        - inf-base
      name: GRP_PUBLIC
      note: Generated

