worker_processes 1;
pid        /tmp/nginx.pid;

events {}

http {
    server {
        listen 8080 default_server;
        listen [::]:8080 default_server;
        location / {
            autoindex on;
            root  /logs;
        }
    }
}