quarkus.http.port=${PORT:8080}
quarkus.log.console.level=INFO
batch.job.namespace=${BATCH_JOB_NAMESPACE:default}
batch.job.deletion.poll-interval-millis=1000
batch.job.deletion.max-attempts=30
batch.execution.stop.graceful.poll-interval-millis=1000
batch.execution.stop.graceful.max-attempts=20
