quarkus.http.port=${PORT:8080}
quarkus.log.level=${LOG_LEVEL:${OP_PROXY_APP_LOG_LEVEL:${QUARKUS_LOG_LEVEL:INFO}}}
quarkus.log.console.level=${LOG_LEVEL:${OP_PROXY_APP_LOG_LEVEL:${QUARKUS_LOG_LEVEL:INFO}}}
batch.job.namespace=${BATCH_JOB_NAMESPACE:default}
batch.execution.stop.graceful.poll-interval-millis=1000
batch.execution.stop.graceful.max-attempts=20
