apiVersion: v2
name: trigger-job-api
description: A Helm chart for Kubernetes Job Manager API
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - jobs
  - api
  - rest
maintainers:
  - name: Your Organization
