{{ $checksum := (printf "%s" (($.Files.Glob "config/*").AsConfig) | sha256sum) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inf-batch-job.name.nginx" . }}
  labels:
    {{ include "inf-batch-job.labels" . | nindent 6 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "inf-batch-job.name.nginx" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ $checksum }}
      labels:
        {{ include "inf-batch-job.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "inf-batch-job.name.nginx" . }}
    spec:
      restartPolicy: Always
      volumes:
        - name: logs-pvc
          persistentVolumeClaim:
            claimName: {{ include "inf-batch-job.name.pvc" . }}
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}
      containers:
        - name: nginx
          image: {{ .Values.pipeline.nginx.image }}
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /logs
              name: logs-pvc
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-conf
          ports:
            - containerPort: 8080
              protocol: TCP