{{- if not (lookup "v1" "PersistentVolumeClaim" .Release.Namespace (include "inf-batch-job.name.pvc" .) ) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "inf-batch-job.name.pvc" . }}
  labels:
    {{- include "inf-batch-job.labels" . | nindent 6 }}
spec:
    accessModes:
      - "ReadWriteMany"
    resources:
      requests:
        storage: 500Mi
{{ else }}
kind: List
apiVersion: v1
items: []
{{- end }}