spring.application.name=trigger-job-api
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.example.triggerjobapi=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Kubernetes
kubernetes.namespace=${K8S_NAMESPACE:default}
kubernetes.job-ttl-seconds=${JOB_TTL_SECONDS:86400}
