quarkus.application.name=inf-javabatch
quarkus.banner.enabled=false
quarkus.log.level=INFO

job.hook.start-url=${START:}
job.hook.status-url=${STATUS:}
job.hook.stop-url=${STOP:}
job.hook.http-timeout-seconds=${HTTP_TIMEOUT_SECONDS:30}
job.hook.stop-wait-seconds=${STOP_WAIT_SECONDS:15}
job.hook.fail-open-on-status-error=${FAIL_OPEN_ON_STATUS_ERROR:true}