apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trigger-job-api.fullname" . }}-config
  labels:
    {{- include "trigger-job-api.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      application:
        name: trigger-job-api
    app:
      log-level: {{ .Values.app.logLevel }}
    kubernetes:
      namespace: {{ .Values.kubernetesApi.namespace }}
      job-ttl-seconds: {{ .Values.kubernetesApi.jobTTLSecondsAfterFinished }}
    server:
      port: {{ .Values.service.targetPort }}
