apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spring-batch-example.fullname" . }}-{{ .Values.cronJob.nameSuffix }}
  labels:
    app.kubernetes.io/name: {{ include "spring-batch-example.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    batch.example/type: spring-batch
spec:
  suspend: {{ .Values.job.suspend }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "spring-batch-example.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        batch.example/type: spring-batch
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      restartPolicy: Never
      containers:
        - name: spring-batch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
