{{- if .Values.scriptJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8s-jobs-example.fullname" . }}-{{ .Values.scriptJob.cronTemplateName }}
  labels:
    {{- include "k8s-jobs-example.commonLabels" . | nindent 4 }}
    batch.example/type: script
spec:
  suspend: true
  backoffLimit: {{ .Values.jobs.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.jobs.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "k8s-jobs-example.commonLabels" . | nindent 8 }}
        batch.example/type: script
    spec:
      serviceAccountName: {{ include "k8s-jobs-example.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: script-job
          image: {{ .Values.scriptJob.image | quote }}
          imagePullPolicy: IfNotPresent
          command:
            {{- toYaml .Values.scriptJob.command | nindent 12 }}
          env:
            {{- toYaml .Values.scriptJob.env | nindent 12 }}
{{- end }}
{{- if .Values.springBatchJob.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8s-jobs-example.fullname" . }}-{{ .Values.springBatchJob.cronTemplateName }}
  labels:
    {{- include "k8s-jobs-example.commonLabels" . | nindent 4 }}
    batch.example/type: spring-batch
spec:
  suspend: true
  backoffLimit: {{ .Values.jobs.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.jobs.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "k8s-jobs-example.commonLabels" . | nindent 8 }}
        batch.example/type: spring-batch
    spec:
      serviceAccountName: {{ include "k8s-jobs-example.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: spring-batch-job
          image: {{ .Values.springBatchJob.image | quote }}
          imagePullPolicy: IfNotPresent
          command:
            {{- toYaml .Values.springBatchJob.command | nindent 12 }}
          env:
            {{- toYaml .Values.springBatchJob.env | nindent 12 }}
{{- end }}
