{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-jobs-example.fullname" . }}-job-runner
  labels:
    {{- include "k8s-jobs-example.commonLabels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-jobs-example.fullname" . }}-job-runner
  labels:
    {{- include "k8s-jobs-example.commonLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-jobs-example.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "k8s-jobs-example.fullname" . }}-job-runner
  apiGroup: rbac.authorization.k8s.io
{{- end }}
