{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-jobs-example.serviceAccountName" . }}
  labels:
    {{- include "k8s-jobs-example.commonLabels" . | nindent 4 }}
{{- end }}
