defaultName: inf-batch-job
defaultImageName: inf-batch-job
cluster: fkds1
replicaCount: 1

autoscaling:
  enabled: false

image:
  registry: image-registry.openshift-image-registry.svc:5000
  repository: cap-template/inf-batch-job
  tag: latest
  pullPolicy: IfNotPresent

service:
  targetPort: 8080

app:
  logLevel: INFO

kubernetesApi:
  namespace: default
  jobTTLSecondsAfterFinished: 300

resources: {}
nodeSelector: {}
affinity: {}
tolerations: []

pipeline:
  repository:
    url: ssh://git@scm.sfa.se:7999/~66030457/inf-batch-poc.git
    revision: main
  image:
    java: image-registry.openshift-image-registry.svc:5000/cap-template/openjdk-17:1.21-1.1739757859-fk1
  nginx:
    image: image-registry.openshift-image-registry.svc:5000/cap-template/nginx:1.29.0-otel-fk1    