[endpoints]
# Update these endpoints to your Spring Batch service in target environment.
springbatchpy.v2.start=https://example.local/api/batch/start
springbatchpy.v2.status=https://example.local/api/batch/status
springbatchpy.v2.stop=https://example.local/api/batch/stop
springbatchpy.v2.restart=https://example.local/api/batch/restart
springbatchpy.v2.summary=https://example.local/api/batch/summary
springbatchpy.v2.help=https://example.local/api/batch/help
