apiVersion: v1
kind: ConfigMap
metadata:
  name: example-job-hooks
data:
  START: "http://example-start-stop-service/start"
  STATUS: "http://example-start-stop-service/status"
  STOP: "http://example-start-stop-service/stop"
  HTTP_TIMEOUT_SECONDS: "30"
  STOP_WAIT_SECONDS: "15"
  FAIL_OPEN_ON_STATUS_ERROR: "true"