apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  suspend: true
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: example-job
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      containers:
        - name: inf-javabatch
          image: example-job:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: example-job-hooks