# Application Configuration
quarkus.application.name=inf-batch-testapp1

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.example".level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] %s%e%n
